version: '3.9'

services:
  backend:
    build: ./backend
    container_name: medical_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./backend/vectorstore:/app/vectorstore

  frontend:
    build: ./frontend
    container_name: medical_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./data:/app/data
